[package]
name = "lists"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
libopenmpt-sys = "0.3.0"
rustfft = "6.2.0"
#cpal = "0.15.3"
#rodio = "0.19.0"
#chrono = "*"
#tempfile = "*"
